// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_m1LtT3FxFjFb45cpKG0ZkrUNP-Io3R4',
    appId: '1:354160164108:web:2a5c2050ee760c12399d29',
    messagingSenderId: '354160164108',
    projectId: 'fin-flow-85539',
    authDomain: 'fin-flow-85539.firebaseapp.com',
    storageBucket: 'fin-flow-85539.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUsC1zB-MFZ0-7mLd4n_II3TPwBwFTUjo',
    appId: '1:354160164108:android:44c333d6c8f3f977399d29',
    messagingSenderId: '354160164108',
    projectId: 'fin-flow-85539',
    storageBucket: 'fin-flow-85539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNffDG7XCEd6zBlx4VwHYBEAz_zfrDNgo',
    appId: '1:354160164108:ios:f668ebb12851bde2399d29',
    messagingSenderId: '354160164108',
    projectId: 'fin-flow-85539',
    storageBucket: 'fin-flow-85539.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNffDG7XCEd6zBlx4VwHYBEAz_zfrDNgo',
    appId: '1:354160164108:ios:f668ebb12851bde2399d29',
    messagingSenderId: '354160164108',
    projectId: 'fin-flow-85539',
    storageBucket: 'fin-flow-85539.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_m1LtT3FxFjFb45cpKG0ZkrUNP-Io3R4',
    appId: '1:354160164108:web:c13e9fb46f68f87d399d29',
    messagingSenderId: '354160164108',
    projectId: 'fin-flow-85539',
    authDomain: 'fin-flow-85539.firebaseapp.com',
    storageBucket: 'fin-flow-85539.firebasestorage.app',
  );
}
